// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8d-CkjhiRJbZH03_q8M81usDbCZlCM0',
    appId: '1:281405835352:web:989de8746163386804622d',
    messagingSenderId: '281405835352',
    projectId: 'aurachat-6e6dd',
    authDomain: 'aurachat-6e6dd.firebaseapp.com',
    storageBucket: 'aurachat-6e6dd.firebasestorage.app',
    measurementId: 'G-89TK73DQMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVKlMJayu49y2Fg-x5taDviRkgiUKhSbQ',
    appId: '1:281405835352:android:9921f854ce5dc0a504622d',
    messagingSenderId: '281405835352',
    projectId: 'aurachat-6e6dd',
    storageBucket: 'aurachat-6e6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvI3Bsl0wdq-8QGGPWaYJeaWDRkBjg3Ug',
    appId: '1:281405835352:ios:6611fe47aca34c8f04622d',
    messagingSenderId: '281405835352',
    projectId: 'aurachat-6e6dd',
    storageBucket: 'aurachat-6e6dd.firebasestorage.app',
    iosBundleId: 'com.example.aniflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvI3Bsl0wdq-8QGGPWaYJeaWDRkBjg3Ug',
    appId: '1:281405835352:ios:6611fe47aca34c8f04622d',
    messagingSenderId: '281405835352',
    projectId: 'aurachat-6e6dd',
    storageBucket: 'aurachat-6e6dd.firebasestorage.app',
    iosBundleId: 'com.example.aniflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf8d-CkjhiRJbZH03_q8M81usDbCZlCM0',
    appId: '1:281405835352:web:69a31ce578116d9f04622d',
    messagingSenderId: '281405835352',
    projectId: 'aurachat-6e6dd',
    authDomain: 'aurachat-6e6dd.firebaseapp.com',
    storageBucket: 'aurachat-6e6dd.firebasestorage.app',
    measurementId: 'G-QJ0NSCHPGV',
  );
}
